<a href="https://colab.research.google.com/github/santiagovillamizarjaimes-collab/Primer-corte/blob/main/m%C3%B3dulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Creando arreglos

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4]])
print(a)
print(b)

[1 2 3 4]
[[1 2]
 [3 4]]


In [5]:
lista = [1, 2, 3]
arr = np.array([1, 2, 3])

In [6]:
lista*2

[1, 2, 3, 1, 2, 3]

In [7]:
arr*2

array([2, 4, 6])

In [8]:
print(arr.shape,
      arr.ndim,
      arr.dtype,
      arr.size)

(3,) 1 int64 3


Arreglos espaciales:

In [11]:
print(np.zeros((2, 3)),
      np.ones((2,2)),
      np.eye(3),
      np.arange(0, 10, 2),
      np.linspace(0, 1, 5))

[[0. 0. 0.]
 [0. 0. 0.]] [[1. 1.]
 [1. 1.]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [0 2 4 6 8] [0.   0.25 0.5  0.75 1.  ]


Indexación

In [12]:
a = np.array([10, 20, 30, 40])
print(a[0], a[-1], a[1:3])

10 40 [20 30]


Indexación de matrices:

In [13]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b[0, 1], b[:1], b[1,:])

2 [[1 2 3]] [4 5 6]


In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a+b

array([5, 7, 9])

In [16]:
a*b

array([ 4, 10, 18])

In [17]:
[x * 2 for x in lista]

[2, 4, 6]

In [18]:
arr * 2

array([2, 4, 6])

In [19]:
b = np.array([1, 2, 3, 4])

In [21]:
print(np.mean(b), np.median(b), np.std(b), np.sum(b), np.min(b), np.max(b))

2.5 2.5 1.118033988749895 10 1 4


Manipulación de arreglos

In [23]:
a = np.array([1, 2, 3, 4, 5, 6])
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.concatenate([a, a])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [25]:
np.concatenate(a.reshape(2, 3))

array([1, 2, 3, 4, 5, 6])

In [26]:
a.reshape(2, 3).flatten()

array([1, 2, 3, 4, 5, 6])

In [27]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [28]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [29]:
print(np. random.rand(10))
print(np.random.randint(0, 10))
print(np.random.randn(3))

[0.27258959 0.15831904 0.00519917 0.4054954  0.34455655 0.1217357
 0.64323577 0.17682735 0.88530703 0.27541271]
2
[-0.34670453  0.11977975  0.24758847]


In [30]:
a = np.array([1, 2, 3, 4, 5])
a[a> 3]

array([4, 5])

In [31]:
a[(a > 2) & (a < 5)]

array([3, 4])

In [32]:
np.where(a > 3, 1, 0)

array([0, 0, 0, 1, 1])

In [33]:
np.where(a <= 3, 2, 3)

array([2, 2, 2, 3, 3])

Ejercicio

In [34]:
arreglo = np.arange(1, 11)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arreglo*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [36]:
c = np.arange(1, 10).reshape(3, 3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
print(np.mean(arreglo))
print(np.std(arreglo))

5.5
2.8722813232690143


In [38]:
condicional = np.where(arreglo > 7, 1, arreglo)
condicional

array([1, 2, 3, 4, 5, 6, 7, 1, 1, 1])

Ahora con pandas